### ISSUE TITLE
GraphQLTest doesn't work 

### ISSUE THREAD

**Issue by Thinkenterprise** [graphql-java-kickstart/graphql-spring-boot#182]
I have problems with the test. I also get the error 404 in the GraphQLResult. The loading of the test query getAllRoutes.graphql works, that I have checked. I think the problem is that the application will not start up, because the spring beans will not be created. I have set a few breakpoints that are not called.

The https://github.com/Thinkenterprise/spring-boot-graphql

Here is the excerpt from my test.

@RunWith(SpringRunner.class)
@GraphQLTest
public class GraphQLRouteTest {

   @Autowired
    private GraphQLTestTemplate graphQLTestTemplate;

    @Test
    public void routes() throws IOException {
        GraphQLResponse response = graphQLTestTemplate.postForResource("getAllRoutes.graphql");
        assertNotNull(response);
        assertTrue(response.isOk());
        assertEquals("1", response.get("$.data.routes.id"));
    }

}

**Comment by biconou** [comment]
@Thinkenterprise I think that the spring context is not loaded because you test class is in package `com.thinkenterprise.test`.
It should be `com.thinkenterprise`.

**Comment by biconou** [comment]
I personnaly got `@GraphQLTest` work on my own project.

**Comment by Thinkenterprise** [comment]
@biconou Thank you for your support!!
I think according to the spring boot convention, the test classes must be below the package by the application class by default. As in my case com.thinkenterprise.* . In other spring boot projects, I do that too and it works. Interestingly, if I put the test class in the com.thinkenterprise package then I get an exception that beans can not be loaded an autowired. If I start the application normally everything is ok. Unfortunately, I do not have an idea anymore. I have invested more than 3 hours today. If you have the time and inclination, maybe you can take a quick look at the project. Maybe I'm just missing something? https://github.com/Thinkenterprise/spring-boot-graphql

**Comment by biconou** [comment]
@Thinkenterprise I am workking on a demo project that works. You may be interested in but il will be Kotlin centric.

**Comment by Thinkenterprise** [comment]
@biconou Yes, if you would share it with me I would be grateful!!

**Comment by oliemansm** [comment]
@Thinkenterprise Just pulled your project and the context loads when I try to run the test. The assertion fails with a 404 however and looks like graphql servlet isn't loaded then. When adding `debug: true` to the `application.yml` you see the Spring Boot debug messages and that certain resolvers can't be found. When adding `@ComponentScan("com.thinkenterprise")` annotation or moving the package up from `test` to `com.thinkenterprise` it can find more. The problem then is that the `RouteRepository` bean apparently is not available. That is because `GraphQLTest` annotation only loads a slice of the Spring config that only loads GraphQL related beans. So any other beans like this repo should either be created using another config or mocked.

**Comment by Thinkenterprise** [comment]
@oliemansm Thanks for your feedback!! @ComponentScan ("com.thinkenterprise") I have already checked with the same result. What I do not understand though, because this method works for other slice tests like @DataJPATest. It certainly has something to do with Spring Data and the creation of proxies.

However, would it not be possible and useful to provide an @GraphQLIntegrationTest annotation that uses @SpringBootTest and provides an instance of GraphQLTestTemplate over autoconfiguration?

If you think that's a good idea I'd support you with the implementation.

**Comment by oliemansm** [comment]
@Thinkenterprise Yeah, I think that's a good idea.

**Comment by Thinkenterprise** [comment]
@oliemansm This works for me. It is possible to set the `@SpringBootTest` annotation directly without your slice `GraphQLTest`. Obviously, the `GraphQLTestTemplate` is always created. The only thing is that the `response.get("$.data.routes.id")` generates a `PathNotFoundException`. I do not understand why, because I have done exactly as you in the example. But I think the main Problem is solved!! So I think we don't need a second annotation like @GraphQLIntegrationTest. The only improvement could be to create the template only when a test is running. But for me it is better that it is always created :-)

``` java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment=WebEnvironment.RANDOM_PORT)
public class GraphQLRouteTest {

    @Autowired
    private GraphQLTestTemplate graphQLTestTemplate;

    @Test
    public void routes() throws IOException {
       
        GraphQLResponse response  = graphQLTestTemplate.postForResource("getAllRoutes.graphql");
        assertNotNull(response);
        assertTrue(response.isOk());
        //assertNotNull(response.get("$.data.routes.id"));
        
    }

}
```

**Comment by Thinkenterprise** [comment]
@oliemansm Perfect, Thanks!!

**Comment by jeet23** [comment]
Reply to https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/182#issuecomment-453658409
I tried this approach but still getting the error `Could not autowire. No beans of 'GraphQLTestTemplate' type found. `
